;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-word
        beginning-of-buffer
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        ccm-mwheel-scroll
        company-indent-or-complete-common
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-buffer
        end-of-visual-line
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        next-error
        scroll-right
        smarter-move-beginning-of-line
        undo-tree-visualize
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        cargo-process-build
        cargo-process-run
        ))
