;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-word
        beginning-of-buffer
        ccm-mwheel-scroll
        company-indent-or-complete-common
        end-of-buffer
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        next-error
        ))

(setq mc/cmds-to-run-once
      '(
        cargo-process-run
        ))
